[workspace]
authors = ["Christoph Schlumpf <7869150+christoph-schlumpf@users.noreply.github.com>"]
channels = [
    "https://conda.modular.com/max-nightly",
    "https://prefix.dev/pixi-build-backends",
    "conda-forge"
]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[package]
name = "example"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.1.*" }

[tasks]
example = { cmd = "pixi run mojo example.mojo" }

[dependencies]
rattler-build = "*"
modular = ">=25.5.0.dev2025070605"
explicit_ref = {git = "https://github.com/christoph-schlumpf/explicit_ref.git"}
