[project]
authors = ["Christoph Schlumpf <7869150+christoph-schlumpf@users.noreply.github.com>"]
channels = [
    "https://conda.modular.com/max-nightly",
    "https://prefix.dev/pixi-build-backends",
    "conda-forge"
]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
preview = ["pixi-build"]

[tasks]
test = { cmd = "pixi run mojo test -D ASSERT=all -I . tests" }
example = { cmd = "pixi run mojo example.mojo" }

[dependencies]
mojo = "*"
