[workspace]
authors = ["Christoph Schlumpf <7869150+christoph-schlumpf@users.noreply.github.com>"]
channels = [
    "https://conda.modular.com/max-nightly",
    "https://repo.prefix.dev/modular-community",
    "https://prefix.dev/pixi-build-backends",
    "conda-forge"
]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
preview = ["pixi-build"]

[package]
name = "explicit_ref"
license = "MIT"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.1.*" }

[tasks]
test = { cmd = "pixi run mojo test -D ASSERT=all -I . tests" }

[dependencies]
max = ">=25.4.0"
rattler-build = "*"
